apiVersion: v1
kind: Service
metadata:
    name: nginx-service
    namespace: develop
spec:
    type: NodePort
    selector:
        app: nginx
    ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 80
